name: secureher
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  carousel_slider: 4.1.1
  webview_flutter: ^4.7.0
  flutter_phone_direct_caller: ^2.2.1
  url_launcher: ^6.1.14
  toastification: ^1.0.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  share_plus: ^7.2.1
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/police-badge.png
    - assets/hospital.png
    - assets/pharmacy.png
    - assets/bus-stop.png
    - assets/route.jpg
